export const locations = [
  "ARGENTINA",
  "Buenos Aires, Argentina",
  "AUSTRALIA",
  "Adelaide, Australia",
  "Brisbane, Australia",
  "Melbourne, Australia",
  "Perth, Australia",
  "Sydney, Australia",
  "AUSTRIA",
  "Wien, Austria",
  "BELGIUM",
  "Antwerpen, Belgium",
  "Bruxelles, Belgium",
  "BRAZIL",
  "Rio de Janeiro, Brazil",
  "São Paulo, Brazil",
  "CANADA",
  "Calgary, Canada",
  "Edmonton, Canada",
  "Halifax, Canada",
  "Montréal, Canada",
  "Ottawa, Canada",
  "Toronto, Canada",
  "Vancouver, Canada",
  "CHILE",
  "Santiago, Chile",
  "CZECH REPUBLIC",
  "Praha, Czech Republic",
  "DENMARK",
  "København, Denmark",
  "FINLAND",
  "Helsinki, Finland",
  "FRANCE",
  "Lyon, France",
  "Marseille, France",
  "Paris, France",
  "GERMANY",
  "Berlin, Germany",
  "Frankfurt am Main, Germany",
  "Hamburg, Germany",
  "Köln, Germany",
  "München, Germany",
  "HONG KONG",
  "ITALY",
  "Milano, Italy",
  "Roma, Italy",
  "JAPAN",
  "MALAYSIA",
  "Kuala Lumpur, Malaysia",
  "MEXICO",
  "México, D.F.",
  "NEW ZEALAND",
  "Auckland, New Zealand",
  "NORWAY",
  "Oslo, Norway",
  "PHILIPPINES",
  "Manila, Philippines",
  "POLAND",
  "Kraków, Poland",
  "Warszawa, Poland",
  "PORTUGAL",
  "Lisboa, Portugal",
  "REPUBLIC OF IRELAND",
  "Dublin, Republic of Ireland",
  "SINGAPORE",
  "Singapore, Singapore",
  "SPAIN",
  "Barcelona, Spain",
  "Madrid, Spain",
  "SWEDEN",
  "Stockholm, Sweden,",
  "SWITZERLAND",
  "Zürich, Switzerland",
  "TAIWAN",
  "THE NETHERLANDS",
  "Amsterdam, Netherlands",
  "TURKEY",
  "İstanbul, Turkey",
  "UNITED KINGDOM",
  "Belfast, United Kingdom",
  "Brighton, United Kingdom",
  "Bristol, United Kingdom",
  "Cardiff, United Kingdom",
  "Edinburgh, United Kingdom",
  "Glasgow, United Kingdom",
  "Leeds, United Kingdom",
  "Liverpool, United Kingdom",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "USA",
  "Arizona",
  "Phoenix, Arizona",
  "Scottsdale, Arizona",
  "Tempe, Arizona",
  "Tucson, Arizona",
  "California",
  "Alameda, California",
  "Albany, California",
  "Alhambra, California",
  "Anaheim, California",
  "Belmont, California",
  "Berkeley, California",
  "Beverly Hills, California",
  "Big Sur, California",
  "Burbank, California",
  "Concord, California",
  "Costa Mesa, California",
  "Culver City, California",
  "Cupertino, California",
  "Daly City, California",
  "Davis, California",
  "Dublin, California",
  "Emeryville, California",
  "Foster City, California",
  "Fremont, California",
  "Glendale, California",
  "Hayward, California",
  "Healdsburg, California",
  "Huntington Beach, California",
  "Irvine, California",
  "La Jolla, California",
  "Livermore, California",
  "Long Beach, California",
  "Los Altos, California",
  "Los Angeles, California",
  "Los Gatos, California",
  "Marina del Rey, California",
  "Menlo Park, California",
  "Mill Valley, California",
  "Millbrae, California",
  "Milpitas, California",
  "Monterey, California",
  "Mountain View, California",
  "Napa, California",
  "Newark, California",
  "Newport Beach, California",
  "Oakland, California",
  "Orange County, California",
  "Palo Alto, California",
  "Park La Brea, California",
  "Pasadena, California",
  "Pleasanton, California",
  "Redondo Beach, California",
  "Redwood City, California",
  "Sacramento, California",
  "San Bruno, California",
  "San Carlos, California",
  "San Diego, California",
  "San Francisco, California",
  "San Jose, California",
  "San Leandro, California",
  "San Mateo, California",
  "San Rafael, California",
  "Santa Barbara, California",
  "Santa Clara, California",
  "Santa Cruz, California",
  "Santa Monica, California",
  "Santa Rosa, California",
  "Sausalito, California",
  "Sonoma, California",
  "South Lake Tahoe, California",
  "Stockton, California",
  "Studio City, California",
  "Sunnyvale, California",
  "Torrance, California",
  "Union City, California",
  "Venice, California",
  "Walnut Creek, California",
  "West Hollywood, California",
  "West Los Angeles, California",
  "Westwood, California",
  "Yountville, California",
  "Colorado",
  "Boulder, Colorado",
  "Denver, Colorado",
  "Connecticut",
  "Hartford, Connecticut",
  "New Haven, Connecticut",
  "Washington, DC",
  "Florida",
  "Fort Lauderdale, Florida",
  "Gainesville, Florida",
  "Miami, Florida",
  "Miami Beach, Florida",
  "Orlando, Florida",
  "Tampa, Florida",
  "Georgia",
  "Atlanta, Georgia",
  "Savannah, Georgia",
  "Hawaii",
  "Honolulu, Hawaii",
  "Lahaina, Hawaii",
  "Iowa",
  "Iowa City, Iowa",
  "Idaho",
  "Boise, Idaho",
  "Illinois",
  "Chicago, Illinois",
  "Evanston, Illinois",
  "Naperville, Illinois",
  "Schaumburg, Illinois",
  "Skokie, Illinois",
  "Indiana",
  "Bloomington, Indiana",
  "Indianapolis, Indiana",
  "Kentucky",
  "Louisville, Kentucky",
  "Louisiana",
  "New Orleans, Louisiana",
  "Massachusetts",
  "Allston, Massachusetts",
  "Boston, Massachusetts",
  "Brighton, Massachusetts",
  "Brookline, Massachusetts",
  "Cambridge, Massachusetts",
  "Somerville, Massachusetts",
  "Maryland",
  "Baltimore, Maryland",
  "Michigan",
  "Ann Arbor, Michigan",
  "Detroit, Michigan",
  "Minnesota",
  "Minneapolis, Minnesota",
  "Saint Paul, Minnesota",
  "Missouri",
  "Kansas City, Missouri",
  "Saint Louis, Missouri",
  "North Carolina",
  "Charlotte, North Carolina",
  "Durham, North Carolina",
  "Raleigh, North Carolina",
  "New Jersey",
  "Newark, New Jersey",
  "Princeton, New Jersey",
  "New Mexico",
  "Albuquerque, New Mexico",
  "Santa Fe, New Mexico",
  "Nevada",
  "Las Vegas, Nevada",
  "Reno, Nevada",
  "New York",
  "Brooklyn, New York",
  "Long Island City, New York",
  "New York, New York",
  "Flushing, New York",
  "Ohio",
  "Cincinnati, Ohio",
  "Cleveland, Ohio",
  "Columbus, Ohio",
  "Oregon",
  "Portland, Oregon",
  "Salem, Oregon",
  "Pennsylvania",
  "Philadelphia, Pennsylvania",
  "Pittsburgh, Pennsylvania",
  "Rhode Island",
  "Providence, Rhode Island",
  "South Carolina",
  "Charleston, South Carolina",
  "Tennessee",
  "Memphis, Tennessee",
  "Nashville, Tennessee",
  "Texas",
  "Austin, Texas",
  "Dallas, Texas",
  "Houston, Texas",
  "San Antonio, Texas",
  "Utah",
  "Salt Lake City, Utah",
  "Virgina",
  "Alexandria, Virginia",
  "Arlington, Virginia",
  "Richmond, Virginia",
  "Vermont",
  "Burlington, Vermont",
  "Washington State",
  "Bellevue, Washington State",
  "Redmond, Washington State",
  "Seattle, Washington State",
  "Wisconsin",
  "Madison, Wisconsin",
  "Milwaukee, Wisconsin",
];
